package model

import (
	"time"
)

// Schema is a structure that defines how schemas will be saved in our Schema Registry.
type Schema struct {
	Id            string           `json:"id,omitempty" bson:"_id,omitempty" firestore:"ID"`
	SchemaType    string           `json:"schema-type" bson:"schema-type" firestore:"schema-type"`
	Autogenerated bool             `json:"autogenerated" bson:"autogenerated" firestore:"autogenerated"`
	Description   string           `json:"description" bson:"description" firestore:"description"`
	CreationDate  time.Time        `json:"creation-date" bson:"creation-date" firestore:"creation-date"`
	Name          string           `json:"name" bson:"name" firestore:"name"`
	SchemaDetails []*SchemaDetails `json:"schemas" bson:"schemas" firestore:"schemas"`
}

type SchemaDetails struct {
	Version       int32  `json:"version" bson:"version" firestore:"version"`
	Specification string `json:"specification" bson:"specification" firestore:"specification"`
	SchemaHash    string `json:"schema-hash" bson:"schema-hash" firestore:"schema-hash"`
}

// InsertInfo is a return value from a DB used when updating the DB
type InsertInfo struct {
	Id      string `json:"id,omitempty" bson:"_id,omitempty"`
	Version int32  `json:"version" bson:"version"`
}
