// Copyright 2020 Syntio Inc.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package database is used a an interface between the REST Server and the underlying database.
//
// It holds general information about the database infrastructure and is the mediator between the REST Server and whatever
// database technology is used underneath.
package database

import (
	"context"

	. "github.com/syntio/schema-registry/model"
	"github.com/syntio/schema-registry/model/dto"
)

//
// DBConnector is an interface between the REST Server and the underlying database.
//
type DBExecutor interface {
	CreateSchema(ctx context.Context, dto *dto.SchemaDTO) (*InsertInfo, bool, error)
	GetSchemaByIdAndVersion(ctx context.Context, id string, version int32) (*Schema, bool)
	UpdateSchemaById(ctx context.Context, id string, schema []byte, autogenerated bool) (*InsertInfo, bool, error)
	GetSchemaVersions(ctx context.Context, id string) (*[]*SchemaDetails, error)
	DeleteById(ctx context.Context, id string) error
}
